config/routes.rb
# frozen_string_literal: true

# Redmine plugin for Custom Workflows
#
# Copyright © 2015-19 Anton Argirov
# Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do
  resources :custom_workflows do
    member do
      # Nothing
    end
  end
  post '/custom_workflows/import', to: 'custom_workflows#import', as: 'import_custom_workflow'
  post '/custom_workflows/:id', to: 'custom_workflows#update'
  get '/custom_workflows/:id/export', to: 'custom_workflows#export', as: 'export_custom_workflow'
  post '/custom_workflows/:id/change_status', to: 'custom_workflows#change_status', as: 'custom_workflow_status'
  put '/custom_workflows/:id/reorder', to: 'custom_workflows#reorder'
end

app/models/custom_workflow.rb
# frozen_string_literal: true

# Redmine plugin for Custom Workflows
#
# Copyright © 2015-19 Anton Argirov
# Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GN73U General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Custom workflow model
class CustomWorkflow < ApplicationRecord

  OBSERVABLES = %i[issue issue_relation issue_attachments user member attachment group group_users project
                   project_attachments wiki_content wiki_page_attachments time_entry version　board message shared].freeze
  PROJECT_OBSERVABLES = %i[issue issue_attachments project project_attachments wiki_content wiki_page_attachments
                           time_entry version member　board message].freeze
  COLLECTION_OBSERVABLES = %i[group_users issue_attachments project_attachments wiki_page_attachments].freeze
  SINGLE_OBSERVABLES = %i[issue issue_relation user member group attachment project wiki_content time_entry version board message]
                       .freeze

  acts_as_list

  has_and_belongs_to_many :projects

  validates :name, uniqueness: true
  validates :author, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, allow_blank: true
  validate :validate_syntax, :validate_scripts_presence,
           if: proc { |workflow| workflow.respond_to?(:observable) and workflow.active? }

  scope :active, -> { where(active: true) }
  scope :sorted, -> { order(:position) }
  scope :for_project, (lambda do |project|
    where(
      %{
        is_for_all = ? OR
        EXISTS (SELECT * FROM #{reflect_on_association(:projects).join_table}
        WHERE project_id = ? AND custom_workflow_id = id)
      },
      true,
      project.id
    )
  end)

  def self.import_from_xml(xml)
    attributes = Hash.from_xml(xml).values.first
    attributes.delete 'id'
    attributes.delete 'exported_at'
    attributes.delete 'plugin_version'
    attributes.delete 'ruby_version'
    attributes.delete 'rails_version'
    name = attributes['name']
    i = 1
    while CustomWorkflow.exists?(name: name)
      name = "#{attributes['name']}_#{i}"
      i += 1
    end
    attributes['name'] = name
    CustomWorkflow.new attributes
  end

  def self.log_message(str, object)
    Rails.logger.info "#{str} for #{object.class} (##{object.id}) \"#{object}\""
  end

  def self.run_shared_code(object)
    # Due to DB migration
    if CustomWorkflow.table_exists? && CustomWorkflow.active.exists?(observable: :shared)
      log_message '= Running shared code', object
      CustomWorkflow.active.where(observable: :shared).sorted.each do |workflow|
        unless workflow.run(object, :shared_code)
          log_message '= Abort running shared code', object
          return false
        end
      end
      log_message '= Finished running shared code', object
    end
    true
  end

  def self.run_custom_workflows(observable, object, event)
    if CustomWorkflow.table_exists? # Due to DB migration
      workflows = CustomWorkflow.active.where(observable: observable)
      if PROJECT_OBSERVABLES.include? observable
        return true unless object.project

        workflows = workflows.for_project(object.project)
      end
      return true unless workflows.any?

      log_message "= Running #{event} custom workflows", object
      workflows.sorted.each do |workflow|
        unless workflow.run(object, event)
          log_message "= Abort running #{event} custom workflows", object
          return false
        end
      end
      log_message "= Finished running #{event} custom workflows", object
    end
    true
  end

  def run(object, event)
    return true unless attribute_present?(event)

    Rails.logger.info "== Running #{event} custom workflow \"#{name}\""
    object.instance_eval self[event]
    true
  rescue RedmineCustomWorkflows::Errors::WorkflowError => e
    Rails.logger.info "== User workflow error: #{e.message}"
    object.errors.add :base, e.message
    false
  rescue StandardError => e
    Rails.logger.error "== Custom workflow #{name}, ##{id} exception: #{e.message}\n #{e.backtrace.join("\n ")}"
    object.errors.add :base, :custom_workflow_error
    false
  end

  def projects_association?
    PROJECT_OBSERVABLES.include? observable.to_sym
  end

  def validate_syntax_for(object, event)
    object.instance_eval(self[event]) if respond_to?(event) && self[event]
  rescue RedmineCustomWorkflows::Errors::WorkflowError => _e
    # Do nothing
  rescue StandardError => e
    errors.add event, :invalid_script, error: e
  end

  def validate_scripts_presence
    fields = case observable.to_sym
             when :shared
               [shared_code]
             when *SINGLE_OBSERVABLES
               [before_save, after_save, before_destroy, after_destroy]
             when *COLLECTION_OBSERVABLES
               [before_add, after_add, before_remove, after_remove]
             else
               []
             end
    errors.add(:base, :scripts_absent) unless fields.any?(&:present?)
  end

  def validate_syntax
    case observable.to_sym
    when :shared
      CustomWorkflow.run_shared_code self
      validate_syntax_for self, :shared_code
    when *SINGLE_OBSERVABLES
      object = observable.camelize.constantize.new
      object.send :instance_variable_set, "@#{observable}", object # compatibility with 0.0.1
      CustomWorkflow.run_shared_code object
      %i[before_save after_save before_destroy after_destroy].each { |field| validate_syntax_for object, field }
    when *COLLECTION_OBSERVABLES
      object = nil
      case observable.to_sym
      when :group_users
        object = Group.new
        object.send :instance_variable_set, :@user, User.new
        object.send :instance_variable_set, :@group, object
      when :issue_attachments
        object = Issue.new
        object.send :instance_variable_set, :@attachment, Attachment.new
        object.send :instance_variable_set, :@issue, object
      when :project_attachments
        object = Project.new
        object.send :instance_variable_set, :@attachment, Attachment.new
        object.send :instance_variable_set, :@project, object
      when :wiki_page_attachments
        object = WikiPage.new
        object.send :instance_variable_set, :@attachment, Attachment.new
        object.send :instance_variable_set, :@page, object
      end
      CustomWorkflow.run_shared_code object
      %i[before_add after_add before_remove after_remove].each { |field| validate_syntax_for object, field }
    end
  end

  def export_as_xml
    attrs = attributes.dup
    attrs['exported-at'] = Time.current.xmlschema
    attrs['plugin-version'] = Redmine::Plugin.find(:redmine_custom_workflows).version
    attrs['ruby-version'] = "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}"
    attrs['rails-version'] = Rails::VERSION::STRING
    attrs.to_xml
  end

  def <=>(other)
    position <=> other.position
  end

  def to_s
    name
  end
end

app/controllers/custom_workflows_controller.rb
# frozen_string_literal: true

# Redmine plugin for Custom Workflows
#
# Copyright © 2015-19 Anton Argirov
# Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Custom workflows controller
class CustomWorkflowsController < ApplicationController
  layout 'admin'
  before_action :require_admin
  before_action :find_workflow, only: %i[show edit update destroy export change_status reorder]

  def reorder
    from = @workflow.position
    to = params[:custom_workflow][:position].to_i
    CustomWorkflow.transaction do
      CustomWorkflow.find_each do |wf|
        if wf.position == from
          wf.position = to
        elsif wf.position >= to && wf.position < from
          # Move up
          wf.position = wf.position + 1
        elsif wf.position <= to && wf.position > from
          # Move down
          wf.position = wf.position - 1
        end
        wf.save
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @workflows = CustomWorkflow.includes(:projects).order(position: :asc)
    respond_to do |format|
      format.html
    end
  end

  def export
    send_data @workflow.export_as_xml, filename: "#{@workflow.name}.xml", type: :xml
  end

  def show
    respond_to do |format|
      format.html { redirect_to edit_custom_workflow_path }
    end
  end

  def new
    @workflow = CustomWorkflow.new
    @workflow.author = cookies[:custom_workflows_author]
    respond_to do |format|
      format.html
    end
  end

  def edit; end

  def import
    xml = params[:file].read
    begin
      @workflow = CustomWorkflow.import_from_xml(xml)
      @workflow.active = false
      if @workflow.save
        flash[:notice] = l(:notice_successful_import)
      else
        flash[:error] = @workflow.errors.full_messages.to_sentence
      end
    rescue StandardError => e
      Rails.logger.warn "Workflow import error: #{e.message}\n #{e.backtrace.join("\n ")}"
      flash[:error] = l(:error_failed_import)
    end
    respond_to do |format|
      format.html { redirect_to(custom_workflows_path) }
    end
  end

  def create
    @workflow = CustomWorkflow.new
    @workflow.position = CustomWorkflow.count + 1
    @workflow.observable = params[:custom_workflow][:observable]
    update_from_params
    respond_to do |format|
      if params.key?(:commit) && @workflow.save
        flash[:notice] = l(:notice_successful_create)
        cookies[:custom_workflows_author] = @workflow.author
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render action: :new }
      end
    end
  end

  def change_status
    respond_to do |format|
      if @workflow.update(active: params[:active])
        flash[:notice] = l(:notice_successful_status_change)
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render action: :edit }
      end
    end
  end

  def update
    respond_to do |format|
      update_from_params
      if params.key?(:commit) && @workflow.save
        flash[:notice] = l(:notice_successful_update)
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render action: :edit }
      end
    end
  end

  def destroy
    @workflow.destroy
    respond_to do |format|
      flash[:notice] = l(:notice_successful_delete)
      format.html { redirect_to(custom_workflows_path) }
    end
  end

  private

  def find_workflow
    @workflow = CustomWorkflow.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def update_from_params
    @workflow.before_save = params[:custom_workflow][:before_save]
    @workflow.after_save = params[:custom_workflow][:after_save]
    @workflow.name = params[:custom_workflow][:name]
    @workflow.description = params[:custom_workflow][:description]
    @workflow.is_for_all = params[:custom_workflow][:is_for_all] == '1'
    @workflow.author = params[:custom_workflow][:author]
    @workflow.active = params[:custom_workflow][:active]
    @workflow.shared_code = params[:custom_workflow][:shared_code]
    @workflow.before_add = params[:custom_workflow][:before_add]
    @workflow.after_add = params[:custom_workflow][:after_add]
    @workflow.before_remove = params[:custom_workflow][:before_remove]
    @workflow.after_remove = params[:custom_workflow][:after_remove]
    @workflow.before_destroy = params[:custom_workflow][:before_destroy]
    @workflow.after_destroy = params[:custom_workflow][:after_destroy]
    @workflow.project_ids = params[:custom_workflow][:project_ids]
  end
end

app/views/custom_workflows/_form.html.erb
<%
  # Redmine plugin for Custom Workflows
  #
  # Copyright © 2015-19 Anton Argirov
  # Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<div class="splitcontent">
  <div class="splitcontentleft">
    <div class="box tabular">
      <p><%= f.text_field :name, required: true %></p>
      <p><%= f.text_field :author, label: :field_custom_workflow_author %>
        <em class="info"><%= l(:text_custom_workflow_author) %></em>
      </p>
      <p><%= f.select :observable,
                      CustomWorkflow::OBSERVABLES.collect { |o| [l("custom_workflow_observable_#{o}"), o] }, {},
                      onchange: 'this.form.submit()',
                      disabled: !@workflow.new_record? %></p>
      <p><%= f.text_area :description, class: 'wiki-edit' %></p>
      <% if @workflow.projects_association? %>
        <p>
          <%= f.check_box :is_for_all, onclick: "checkAndDisable('custom_workflow_enabled_projects', this.checked);",
                label: :field_enabled_for_all_projects %>
        </p>
      <% end %>
      <p><%= f.check_box :active, label: l(:field_active) %></p>
    </div>
  </div>
  <% if @workflow.projects_association? %>
    <div class="splitcontentright">
      <div class="box tabular">
        <%= content_tag 'fieldset', id: 'custom_workflow_enabled_projects' do %>
          <legend>
            <%= toggle_checkboxes_link("#custom_workflow_enabled_projects input[type=checkbox]") %>
            <%= l(:label_project_plural) %>
          </legend>
          <%= render_project_nested_lists(Project.visible.active) do |p| %>
            <%= content_tag 'label',
                  check_box_tag('custom_workflow[project_ids][]', p.id,
                     @workflow.project_ids.include?(p.id) || @workflow.is_for_all?, id: nil,
                     disabled: @workflow.is_for_all?) + ' ' + h(p), class: 'block' %>
          <% end %>
          <%= hidden_field_tag 'custom_workflow[project_ids][]', '', id: nil %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="custom_workflow_scripts" class="box tabular">
  <fieldset>
    <legend><%= l(:label_workflow_scripts) %></legend>
    <% observable = @workflow.observable.to_sym %>
    <div class="custom-workflow-info">
      <em class="info"><%= l("text_custom_workflow_#{observable}_code_note") %></em>
    </div>
    <% case observable %>
    <% when :shared %>
      <%= f.text_area :shared_code, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
    <% when *CustomWorkflow::COLLECTION_OBSERVABLES %>
      <% collapsed = !(@workflow.before_add.present? || @workflow.after_add.present? || @workflow.errors[:base].present?) %>
      <fieldset class="collapsible <%= collapsed ? 'collapsed' : '' %>">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed"><%= l(:label_add_workflows) %></legend>
        <div class="<%= collapsed ? 'custom-workflow-hidden' : '' %>">
          <div class="splitcontent">
            <div class="splitcontentleft">
              <%= f.text_area :before_add, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
            </div>
            <div class="splitcontentright">
              <%= f.text_area :after_add, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
            </div>
          </div>
        </div>
      </fieldset>
      <% collapsed = !(@workflow.before_remove.present? || @workflow.after_remove.present?) %>
      <fieldset class="collapsible <%= collapsed ? 'collapsed' : '' %>">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed"><%= l(:label_remove_workflows) %></legend>
        <div class="<%= collapsed ? 'custom-workflow-hidden' : '' %>">
          <div class="splitcontent">
            <div class="splitcontentleft">
              <%= f.text_area :before_remove, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
            </div>
            <div class="splitcontentright">
              <%= f.text_area :after_remove, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
            </div>
          </div>
        </div>
      </fieldset>
    <% when *CustomWorkflow::SINGLE_OBSERVABLES %>
      <% collapsed = (not (@workflow.before_save.present? or @workflow.after_save.present? or @workflow.errors[:base].present?)) %>
      <fieldset class="collapsible <%= collapsed ? 'collapsed' : '' %>">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed"><%= l(:label_save_workflows) %></legend>
        <div class="<%= collapsed ? 'custom-workflow-hidden' : '' %>">
          <div class="splitcontent">
            <div class="splitcontentleft">
              <%= f.text_area :before_save, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
              <% if observable == :issue %>
                <em class="info"><%= l(:text_custom_workflow_before_save_note) %></em>
              <% end %>
            </div>
            <div class="splitcontentright">
              <%= f.text_area :after_save, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
              <% if observable == :issue %>
                <em class="info"><%= l(:text_custom_workflow_after_save_note) %></em>
              <% end %>
            </div>
          </div>
        </div>
      </fieldset>
      <% collapsed = !(@workflow.before_destroy.present? || @workflow.after_destroy.present?) %>
      <fieldset class="collapsible <%= collapsed ? 'collapsed' : '' %>">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed"><%= l(:label_destroy_workflows) %></legend>
        <div class="<%= collapsed ? 'custom-workflow-hidden' : '' %>">
          <div class="splitcontent">
            <div class="splitcontentleft">
              <%= f.text_area :before_destroy, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
              <em class="info"><%= l(:text_custom_workflow_before_destroy_note) %></em>
            </div>
            <div class="splitcontentright">
              <%= f.text_area :after_destroy, cols: 40, rows: 20, wrap: 'off', class: 'custom_workflow_script' %>
            </div>
          </div>
        </div>
      </fieldset>
    <% end %>
  </fieldset>
</div>

<%= wikitoolbar_for :custom_workflow_description %>

app/views/custom_workflows/edit.html.erb
<%
  # Redmine plugin for Custom Workflows
  #
  # Copyright © 2015-19 Anton Argirov
  # Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<h2><%= link_to l(:label_custom_workflow_plural), custom_workflows_path %> &#187; <%= @workflow %></h2>

<%= error_messages_for 'workflow' %>

<%= labelled_form_for @workflow do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= submit_tag l(:button_save) %>
<% end %>

<% html_title l(:label_custom_workflow_plural), @workflow, l(:label_administration) %>

app/views/custom_workflows/index.html.erb
<%
  # Redmine plugin for Custom Workflows
  #
  # Copyright © 2015-19 Anton Argirov
  # Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% html_title l(:label_custom_workflow_plural) %>
<div class="contextual">
  <%= link_to l(:label_custom_workflow_new), new_custom_workflow_path, class: 'icon icon-add' %>
  <%= actions_dropdown do %>
    <%= link_to l(:label_custom_workflow_import), '#', class: 'icon icon-move',
                onclick: "showModal('import-dialog', '450px'); return false;" %>
    <% end %>
</div>

<h2><%= l(:label_custom_workflow_plural) %></h2>

<div class="autoscroll">
  <% if @workflows.any? %>
    <table class="custom-workflows list" data-hascontextmenu="true">
      <thead>
      <tr>
        <th><%= l(:field_name) %></th>
        <th><%= l(:field_observable) %></th>
        <th><%= l(:field_author) %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @workflows.each do |workflow| %>
        <tr class="<%= cycle('odd', 'even') %> <%= 'disabled' unless workflow.active? %>">
          <td class="name"><%= link_to workflow.name, edit_custom_workflow_path(workflow) %></td>
          <td class="observable"><%= l("custom_workflow_observable_#{workflow.observable}") %></td>
          <td class="author"><%= mail_to workflow.author if workflow.author.present? %></td>
          <td class="buttons">
            <%= reorder_handle workflow, url: url_for(action: 'reorder', id: workflow) %>
            <% if workflow.active? %>
              <%= link_to l(:button_custom_workflow_deactivate), custom_workflow_status_path(workflow, active: false),
                          class: 'icon icon-lock', method: :post %>
            <% else %>
              <%= link_to l(:button_activate), custom_workflow_status_path(workflow, active: true),
                          class: 'icon icon-unlock', method: :post %>
            <% end %>
            <%= link_to l(:label_custom_workflow_export), export_custom_workflow_path(workflow),
                        class: 'icon icon-download', method: :get %>
            <%= link_to l(:button_delete), workflow, class: 'icon icon-del', data: { confirm: l(:text_are_you_sure) },
                        confirm: l(:text_are_you_sure), method: :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>
<div id="import-dialog" class="custom-workflow-hidden">
  <h3 class="title"><%= l(:label_custom_workflow_import) %></h3>
  <%= form_tag import_custom_workflow_path, :multipart => true do %>
    <p>
      <%= l(:field_custom_workflow_file) %>:
    </p>
    <p>
      <%= file_field_tag 'file', accept: 'application/xml' %>
    </p>
    <p class="buttons">
      <%= submit_tag l(:button_import), name: nil, onclick: 'hideModal(this);' %>
      <%= submit_tag l(:button_cancel), name: nil, onclick: 'hideModal(this);', type: 'button' %>
    </p>
  <% end %>
</div>

<%= javascript_tag do %>
  $(function() {
      $("table.custom-workflows tbody").positionedItems();
  });
<% end %>

app/views/custom_workflows/new.html.erb
<%
  # Redmine plugin for Custom Workflows
  #
  # Copyright © 2015-19 Anton Argirov
  # Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<h2><%= link_to l(:label_custom_workflow_plural), custom_workflows_path %> &#187; <%= l(:label_custom_workflow_new) %></h2>

<%= error_messages_for 'workflow' %>

<%= labelled_form_for @workflow do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= submit_tag l(:button_create) %>
<% end %>

<% html_title l(:label_custom_workflow_plural), l(:label_custom_workflow_new), l(:label_administration) %>

app/views/custom_workflows/reorder.js.erb
<%
# encoding: utf-8
#
# Redmine plugin for Custom Workflows
#
# Copyright © 2015-19 Anton Argirov
# Copyright © 2019-23 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

location.replace('<%= custom_workflows_path %>');